### PR TITLE
Works on Home Page for NY Times clone

### PR DESCRIPTION
**Pull request by KabohaJeanMark**
**What does this PR do?**
It adds the code in multiple small commits that have been worked on to create a clone for the NY Times site
It's a home page with the following
- a sticky footer
- multiple social media icons worked on using font-awesome
- many images and a YouTube video embedded
- positioning is done using all 3 CSS techniques floating, flexbox and CSS grid.
- styled to act as a clone for [this article on the NY times page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)

[Live Site of Clone](https://kabohajeanmark-nytimes-clone.onrender.com/)

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @KabohaJeanMark**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] the nyt logo should be an actual png, not some text. that applies to the footer and navbar.
- [x] in the original page, the headline image is a little bigger. please make sure to make it so.
- [x] the width that you are giving for the text section is too narrow, try to give it a little more width.
- [x] the theory of inflation section shouldn't be an image, you must take the image background from the original page and add text on top of it.
- [x] the editor's picks section doesn't look like the original one.  please make sure that it looks like the original one.
- [x] the suggested newsletter, most popular, and More in Space and Astronomy sections are all missing. please make sure to add them.
- [x] the footer doesn't look like the original one, please make sure that it an exact replica of the original.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by KabohaJeanMark** [comment]
> MahmoudMohammad

Thanks a bunch for the quick ASK Feedback. I have finished implementing the recommended changes.

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi Marcus!
Great job so far:clap::clap:. The project looks very much like the original:blush:. However, we still need to make a few changes to get this project approved:muscle:.**

**Navigation bar**

- [x] It has a "Hamburger button", a search icon, and a link with text on the leftmost side. Kindly make the text a link using the href attribute and anchor tag.

- [x] The NY Times logo is a link. Currently, it's not a link. Kindly make it a link.

Make the above-required changes and when you are ready, request another review.
You can drop your questions :point_down: and tag my name or ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan

**Comment by KabohaJeanMark** [comment]
Hello @enaburekhan.
Thanks for the feedback. :clap::clap: 
I have worked on all the changes.

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @KabohaJeanMark 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] MIT License is missing from the Readme file. Please update it.
### The Theory of Inflation
- [x] Please fix this issue

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://rawcdn.githack.com/KabohaJeanMark/NewYorkTimes-clone/4aee9a291b1c7181eedf08171d2ed190040b5fb5/index.html)|
|:---:|:---:|
|source-page|clone|
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by KabohaJeanMark** [comment]
Thanks :clap::clap: for your feedback @umairarshadbutt. I have implemented all of it :blush:
- I added the MIT link to the License on the README 
- I am using media queries to add responsiveness and adjusting the paragraph sizes and their absolute positioning on top of the relative image to complete all the feedback :muscle:

**Review by christianotieno — APPROVED** [review]
## Project Approved 🍾 
Hello @KabohaJeanMark 👋 
Things look great now.  Congratulations 👍 
On to the next one 🥇 
### Happy coding 💻 
#### Christian Otieno (CR)

**Pull request merged**
